<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Riok.Mapperly" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.File" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DNAustria.Dal\DNAustria.Dal.csproj" />
      <ProjectReference Include="..\DNAustria.Domain\DNAustria.Domain.csproj" />
      <ProjectReference Include="..\DNAustria.Logic\DNAustria.Logic.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="logs\" />
    </ItemGroup>
</Project>
