<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageVersion>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.1.26104.118" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
        <PackageVersion Include="Riok.Mapperly" Version="4.2.1" />
        <PackageVersion Include="Scalar.AspNetCore" Version="2.12.50" />
        <PackageVersion Include="Serilog" Version="4.3.2-dev-02419" />
        <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageVersion Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
    </ItemGroup>
</Project>