export * from './auth.service';
import { AuthService } from './auth.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './organizations.service';
import { OrganizationsService } from './organizations.service';
export * from './public.service';
import { PublicService } from './public.service';
export const APIS = [AuthService, ContactsService, EventsService, LocationsService, OrganizationsService, PublicService];
