/**
 * DNAustria.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreateUpdateDto } from './addressCreateUpdateDto';


export interface CreateUpdateLocationDto { 
    name: string;
    latitude: number;
    longitude: number;
    address?: AddressCreateUpdateDto | null;
}

