name: CI

















        run: dotnet test --no-build --configuration Release --verbosity normal      - name: Test        run: dotnet build --no-restore --configuration Release      - name: Build        run: dotnet restore      - name: Restore          dotnet-version: '7.0.x'        with:        uses: actions/setup-dotnet@v4      - name: Setup .NET      - uses: actions/checkout@v4    steps:    runs-on: windows-latest  build:
njobs:non: [push, pull_request]